### ISSUE TITLE
Add a model file path collector in `models/__init__.py`

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv_zoo#120]
We now have lots of configs for benchmark and each of them has a hard written model path like the following:

```yaml
Model:
  name: "YuNet"
  modelPath: "models/face_detection_yunet/face_detection_yunet_2022mar.onnx"
```

This is not convenient and bad for automation when it comes to upgrade a model and benchmark int8-quantized model. To address this problem, Add a model file path collector `models/__init__.py` and also add an option in benchmark configs to allow loading int8-quantized models.
